[server]
maxUploadSize = 2048
headless = true

[theme]
base = "light"
primaryColor = "#000000"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#000000"
font = "sans serif"

